### ISSUE TITLE
SubWallet Interactive with other device for signature

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#150]
### Overview
Signer with manage account and keep private key and allow to create signature for any transaction. Most of signer require passphase to unlock private key before create signature. DApp, Extension Wallet, Hardware Wallet, Mobile Signer can become signer if it keep private key of an account. 

There are some signing data usecase depend on which object contain private key:
1. **DApp keep private key**
  a. This is most simplest case. DApp will create transaction and sign transaction with private key that it own.
2. **Extension Wallet keep private key, this case is very popular key**
  a. Some Wallet Extension like SubWallet have some features like a DApp. When user perform some features that required signature, this case will be the same with 1a.
  b. DApp will create transaction and keyring on DApp will request signature from Extension via extension signature.
  c. DApp on mobile can be import account from QR code. Anytime required signature DApp need to push data to Extension Wallet and get signature result by QR.
3. **Hardware Wallet keep private key, this is nearly the most security**
  a. DApp direct connect to hardware wallet via usb connection and it need to import account from hardware wallet. Whenver imported account request signature, it required Hardware Wallet connect and sign data with its passphase.
  b. DApp use injected account from Extension and Extension import account from hardware. With DApp this case is same with 2a but with Extension it need to import account from Hardware and connect to this device to get transaction signature.
4. **Mobile Signer keep private key**. This case near the same with Hardware Wallet but Mobile Signature will use QR code to interact with extension or DApp
  a. DApp direct connect to hardware wallet via usb connection and it need to import account from QR code. Whenver imported account request signature DApp with send and get payload via QR code.
  b. DApp use injected account from Extension and Extension import account from hardware. With DApp this case is same with 2a but with Extension it need to import account from and request signature by send and get data via QR code.

![image](https://user-images.githubusercontent.com/11567273/163176139-bd9aaf5b-f5f8-4291-8afc-74dfb8fd07f5.png)

### Use QR with signer
- Import account via QR:
  - Data: `AccountType:Address:PublicKey:AccountName`
  - Example: `substrate:5HL6xpAbHnxCwW2uUqQ5dmev2wo2FQkpUEfmXrzmzTFkWMRo:0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e:Westend root`
- Import ETH Account:
  - Data: `ethereum:(details = address | address "@" chainid | address "@" chainid ":" name)`
  - EG: `ethereum:0x4f604e0FECf7F78B64a564C343b870bB4608700c@1284:EVM-Account-001`
- Signature request: `createSignPayload(address, cmd, payload, genesisHash)` in package `@polkadot/react-qr`
- Signature: Sign result eg: `01d6b5a7d39598c76c5754448e0e55a258088cb03a573dd04db06e16be3eafb854285407903b8ce551255011e0ae52226f52ab7a31d38f1f3fd1f0a09349e2b989`
- Research Mindmap
  ![SubWallet   Signer](https://user-images.githubusercontent.com/11567273/167535790-36bce5f8-f738-407c-9af7-6c51610466ea.png)
- Standard: [folllow this article](https://github.com/maciejhirsz/uos)

## Requirements
SubWallet now work ok with case 2a, 2b It hold private key and can sign for these transaction. 
- We need to test does our wallet work well with case 3a.
- We also compitable with case 2c, 4b

## Todo List
These step will help us response for all requiredment 
### Research
- [x] How to hardware wallet work?
- [x] How to mobile signer work?

### Test again
- [x] Sign Transactions with hardware wallet
- [x] Create Account via Ledger
- [x] Send / Receive Assets
### Implement
Can use 2 lib `@polkadot/react-singer` & `@polkadot/react-qr` with these component `QrDisplayPayload` and `QrScanSignature`
- [x] #316
- [x] #317
- [x] #315
### Staking
- [x] Stake
- [x] UnStake
- [x] Withdraw

**Comment by saltict** [comment]
## Basic knowledge
### Overview
Signer with manage account and keep private key and allow to create signature for any transaction. Most of signer require passphase to unlock private key before create signature. DApp, Extension Wallet, Hardware Wallet, Mobile Signer can become signer if it keep private key of an account. 

There are some signing data usecase depend on which object contain private key:
1. **DApp keep private key**
  a. This is most simplest case. DApp will create transaction and sign transaction with private key that it own.
2. **Extension Wallet keep private key, this case is very popular key**
  a. Some Wallet Extension like SubWallet have some features like a DApp. When user perform some features that required signature, this case will be the same with 1a.
  b. DApp will create transaction and keyring on DApp will request signature from Extension via extension signature.
  c. DApp on mobile can be import account from QR code. Anytime required signature DApp need to push data to Extension Wallet and get signature result by QR.
3. **Hardware Wallet keep private key, this is nearly the most security**
  a. DApp direct connect to hardware wallet via usb connection and it need to import account from hardware wallet. Whenver imported account request signature, it required Hardware Wallet connect and sign data with its passphase.
  b. DApp use injected account from Extension and Extension import account from hardware. With DApp this case is same with 2a but with Extension it need to import account from Hardware and connect to this device to get transaction signature.
4. **Mobile Signer keep private key**. This case near the same with Hardware Wallet but Mobile Signature will use QR code to interact with extension or DApp
  a. DApp direct connect to hardware wallet via usb connection and it need to import account from QR code. Whenver imported account request signature DApp with send and get payload via QR code.
  b. DApp use injected account from Extension and Extension import account from hardware. With DApp this case is same with 2a but with Extension it need to import account from and request signature by send and get data via QR code.

![image](https://user-images.githubusercontent.com/11567273/163176139-bd9aaf5b-f5f8-4291-8afc-74dfb8fd07f5.png)

### Use QR with signer
- Import account via QR:
  - Data: `AccountType:Address:PublicKey:AccountName`
  - Example: `substrate:5HL6xpAbHnxCwW2uUqQ5dmev2wo2FQkpUEfmXrzmzTFkWMRo:0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e:Westend root`
- Signature request: `createSignPayload(address, cmd, payload, genesisHash)` in package `createSignPayload(address, cmd, payload, genesisHash)`
- Signature: Sign result eg: `01d6b5a7d39598c76c5754448e0e55a258088cb03a573dd04db06e16be3eafb854285407903b8ce551255011e0ae52226f52ab7a31d38f1f3fd1f0a09349e2b989`

## Requirements
SubWallet now work ok with case 2a, 2b It hold private key and can sign for these transaction. 
- We need to test does our wallet work well with case 3a.
- We also compitable with case 2c, 4b

## Todo List
These step will help us response for all requiredment 
### Research
- [x] How to hardware wallet work?
- [x] How to mobile signer work?

### Test again
- [ ] Sign with hardware wallet
### Implement
Can use 2 lib `@polkadot/react-singer` & `@polkadot/react-qr` with these component `QrDisplayPayload` and `QrScanSignature`
- [ ] QR display / QR Scan
- [ ] Sign with mobile signer via QR
- [ ] Sign with extension via QR

**Comment by sokol142** [comment]
Pls check some issues:

- [ ] Account imported via QR-Signed still enable Export Private Key button on the Receive screen
![image](https://user-images.githubusercontent.com/102292476/172747430-209bddfd-25ae-4066-865e-e4eec75bc5aa.png)

- [ ] Can't cancel "Scan signature via camera" action
![image](https://user-images.githubusercontent.com/102292476/172747682-37aaa60a-761d-4bee-8b9d-1c115211c828.png)

**Comment by sokol142** [comment]
- [ ] Don't show checkbox "Remember password" on the Scan QR screen when user perform transfer tokens of the EVM Chain
![image](https://user-images.githubusercontent.com/102292476/174972174-da588464-e909-4f73-958d-87132b11565f.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./337-merge-build-0.4.6-1656046324651.zip

Pls check issues:

- [ ] Can not send NFT from QR Account & Ledger account
![150_SendNFT_LedgerAcc](https://user-images.githubusercontent.com/102292476/175865329-1c0959bc-0338-447a-acf3-ba5b579e60fd.gif)
![150_SendNFT_QRAcc](https://user-images.githubusercontent.com/102292476/175865340-e5f4c818-1c49-46d4-ba03-b56096d18b41.gif)
- [ ] Improve experience when importing Ledger Account
- Expected: Keep the current chain of the Ledger account & not allow switch chain

**Comment by sokol142** [comment]
- [ ] Display incorrect screen when user click on Cancel XCM transfer
Steps:
1. Open the extension
2. Go to the XCM transfer screen
3. Input valid data then click on Transfer button
4. Click on Sign via QR
5. On the Authorize Transaction - Scan QR code screen, click on Cancel button
6. Back to Send Fund screen then click on Transfer button again
Actual: Navigate to Scan QR code
Expected: Navigate to the Sign via QR code screen 
To reproduce: https://www.loom.com/share/9299c4d1a5f94cbb93dccefbb9d6e405

- [ ] Bug UI
![image](https://user-images.githubusercontent.com/102292476/176169203-95a18c7e-38f3-43b8-a993-bbe0e0acc034.png)
![image](https://user-images.githubusercontent.com/102292476/176169262-e5eb8f73-3e39-46bf-b3cc-3cfee4b2e690.png)
![image](https://user-images.githubusercontent.com/102292476/176169332-c4cbde86-f113-4499-83ce-effda7c68825.png)
![image](https://user-images.githubusercontent.com/102292476/176169533-8123f2da-2caa-40c2-8c80-8567a6ca7aa2.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./337-merge-build-0.4.7-1656662663807.zip
Check issues:

- [ ] Click on Cancel button but can't cancel, the popup is not turn off
![image](https://user-images.githubusercontent.com/102292476/176873871-2a386d36-e4b9-4d28-bfe4-568a0c2cb9b1.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./337-merge-build-0.4.9-1657795530326.zip

- [ ] Check case send asset from Ledger Account (Kusama)
![image](https://user-images.githubusercontent.com/102292476/179934317-3274d1d7-1b88-425b-8886-962638f0036d.png)

**Comment by sokol142** [comment]
@hieudd Screenshot for this feature.
[QR_Ledger_Account.zip](https://github.com/Koniverse/SubWallet-Extension/files/9148022/QR_Ledger_Account.zip)

**Comment by S2kael** [comment]
### Ledger Kusama

- Update App Kusama on Ledger Live to latest version


https://user-images.githubusercontent.com/41369298/181150703-c433595a-1ccc-4fb3-b545-a5e961e006f6.mp4

**Comment by hieudd** [comment]
@S2kael update style follow this Design:

- [ ] Case 1: With Ledger Device: 

- Description: Update style to have more space to display alert) 
- Design: https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=4280%3A13265&scaling=min-zoom&page-id=4%3A14

- [ ] Case: QR Signer: 

- Update style: Update the style according to the design
- https://www.figma.com/file/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=4292%3A14421

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./337-merge-build-0.5.3-1659612112422.zip
### QR signer

- [ ] Case: Private Key in Cold Wallet
Tested with Stylo.
Validation passed for cases:
- Attach address
- Send fund
- XCM transfer
- Send NFT
- Staking: Stake, Unstake, Withdraw
- Connect dApp & send asset via dApp

- [ ] Case: Private Key in Extension
Validation passed for sign transaction in cases:
- Send fund
- XCM transfer
- Send NFT
- Staking: Stake, Unstake, Withdraw
- Connect dApp & send asset via dApp
