### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#1532]
**Is your feature request related to a problem? Please describe.**
We need multi-language support for SubWallet apps, including Extension and Mobile App. Supported languages include
- [x] China
- [x] Vietnamese
- [x] Russia / Ukraina
- [x] Japan
- [ ] Portuguese

**Tasks to be performed include:**

- [x] Export multi-language files
- [x] Send a request to the content team
- [ ] Import language file
   - #1630
   - https://github.com/Koniverse/SubWallet-Extension/issues/1640
   - https://github.com/Koniverse/SubWallet-Extension/issues/1658
   - https://github.com/Koniverse/SubWallet-Extension/issues/2123

**Comment by nguyenduythuc** [comment]
English i18n file with typescript format:
[en_US.ts.zip](https://github.com/Koniverse/SubWallet-Extension/files/11732736/en_US.ts.zip)

**Comment by saltict** [comment]
[locales.zip](https://github.com/Koniverse/SubWallet-Extension/files/11732965/locales.zip)

**Comment by Sokol142196** [comment]
Will resolve later in https://github.com/Koniverse/SubWallet-Extension/issues/2123
