### ISSUE TITLE
WebApp - AirDrop Tracking

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#1700]
**Is your feature request related to a problem? Please describe.**
Implement feature airdrop tracking for product web app
https://twitter.com/leap_cosmos/status/1669381891596902400

List task:

- [x] Organize information on Strapi: @anhntk54 
  - Link doc: https://www.notion.so/subwallet/Li-t-k-c-c-th-ng-tin-v-danh-s-ch-mission-pool-cho-t-nh-n-ng-Airdrop-0577e14e5b624eb4b2924ba5865946db?pvs=4#813965137f82454ab029c2f831a95fb9
- [x] Implement Mission Pool: @lw-cdm 
  - Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=11173-199586&mode=design&t=jGgnQcwtDo6Fh63K-4

**Comment by Sokol142196** [comment]
Version test: https://9f2b9230.subwallet-yield.pages.dev/mission-pools

- [ ] Handle case scrolling

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/18f9cab0-f1aa-4585-a988-362ea5a26ed5)

**Comment by Sokol142196** [comment]
Version test: https://edbeb6c4.subwallet-webapp.pages.dev/

- [ ] Show Rewards = $NaN even though Total rewards > 0

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f1901bda-e787-4e8b-b815-3517dd646852)

**Comment by Sokol142196** [comment]
Version test: https://45bc2cca.subwallet-webapp.pages.dev/

- [ ] Handle case multi network

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b1c4c80c-0a65-4afc-91a0-477654d3fe79)
