### ISSUE TITLE
WebApp  - Update neway to fetch history data of an account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2116]
**Describe the task**
WebApp - Update neway to fetch history data of an account. Update UX - User need select account to get transaction history

# Data types:
- Transfer history

# Networks
- All subscan network on ChainList (update to version 0.2.25-beta.0)
  - Field: extraInfo?.subscanSlug

# Todo:
- [x] Implement on WebApp
- Implement on Extension -> Resolve in https://github.com/Koniverse/SubWallet-Extension/issues/2223

**Comment by Sokol142196** [comment]
Version test: https://04cf88ec.subwallet-webapp.pages.dev/home/tokens

Please check the issues:

- [ ] Do not show the history detail screens after performing transaction successfully
  - Example: Performing transfer TZERO token
  - Expect: Show history detail screen

- [ ] Update filter criteria
  - Actual: Still show EVM chain although select Substrate account
  - Expect: 
    - Select account = Substrate acc then filter network = Substrate networks and
    - Select network = Substrate network then filter acc = Substrate acc

**Comment by lw-cdm** [comment]
> Version test: https://04cf88ec.subwallet-webapp.pages.dev/home/tokens
> 
> Please check the issues:
> 
> * [x]  Do not show the history detail screens after performing transaction successfully
>   
>   * Example: Performing transfer TZERO token
>   * Expect: Show history detail screen
> * [ ]  Update filter criteria
>   
>   * Actual: Still show EVM chain although select Substrate account
>   * Expect:
>     
>     * Select account = Substrate acc then filter network = Substrate networks and
>     * Select network = Substrate network then filter acc = Substrate acc

Note: there are some modules related to "Transaction done" are affected:
- Staking (action Claim Reward and Withdraw in More Actions modal)
- Earning
- Send fund

**Comment by Sokol142196** [comment]
Version test: SubWallet v 1.1.24 - 1122006
Continue improve in https://github.com/Koniverse/SubWallet-Extension/issues/2326 and https://github.com/Koniverse/SubWallet-Extension/issues/2179
