### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#2931]
- [x] Add backup RPC for Liberland: wss://liberland-rpc.dwellir.com
----
=> Implement later
- Support Enjin native staking https://github.com/Koniverse/SubWallet-ChainList/issues/202
- Support Enjin nomination pool staking
----
- [x] Add STINK on  hydradx https://github.com/Koniverse/SubWallet-ChainList/issues/210
- [x] Add STINK on statemint
- [x] Add group asset for STINK
- [x] Add PINK on Base https://github.com/Koniverse/SubWallet-ChainList/issues/211
----
- [x] Add XCM Beefy on hydradx -> statemint (temporary disable)
- [x] Add XCM Beefy on statemint -> hydradx (temporary disable)
- [x] Add XCM STINK on hydradx -> statemint (temporary disable)
- [x] Add XCM STINK on statemint -> hydradx (temporary disable)
----
=> Implement later
- Support AlephZero NFT https://github.com/Koniverse/SubWallet-ChainList/issues/206

----

- [x] Support Paseo network: https://github.com/Koniverse/SubWallet-Extension/issues/2591

**Comment by bluezdot** [comment]
Has PINK on base: 0xb9d10940dae76c3e50d422c754009eeda22b4ea0

**Comment by nampc1** [comment]
To be released:
- [ ] Support STINK on Statemint, HydraDX
- [ ] ENJIN native staking
- [ ] Add RPC for Liberland

**Comment by haiyenvu23** [comment]
- https://github.com/Koniverse/SubWallet-Extension/issues/2591
Version test : http://file.cdmteck.com/s/AonBXDHkteZaJNs
Data test : 5EycVndjB9qTP5EKH8duY6C6Nu4hVm9SBbUBymAryWz1Yh4a

Validation passed in case :

- Displays the correct balance of the account when on network


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/72b30a5b-6894-472a-acde-a647b7a721c9)


- Can perform Send/Receive tokens


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c048d57c-5846-40da-87b0-d2f1e3573a98)


- Check case when updated version
- Display correct network information

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7c7109bb-5f31-4029-ac36-1c51080b2662)

- Display correct token information

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/041bf76a-58be-4dfd-b601-13d9086f64c6)
