### ISSUE TITLE
Update signing flow with metadata 

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3306]
### Todo:
- [x] Recheck getting `metadata` data.
- [x] Change priority to get registry to signing.
- [ ] Improve logic check and add extra info
- [ ] Subscribe metadata on UI side

### Optional
- Add logic check network active for Ledger case
- Required to add the network in case sign dApp request (if necessary)

### Considering
- Subscribe metadata when chain update

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/c3b6oLeq4e3M5RE
Validation passed in case : 
- Install/Update version
- Check transaction execution when setting up When needed mode
- Check transaction execution when setting up Always required mode
- Check transfer/send NFT/stake with normal account, ledger account, QR account (currently cannot sign because its app cannot update metadata)
- Check sign transaction with dapp (normal account, ledger account): polkadotjs, subconnect, webapp, https://app.mimir.global/
- Check transaction execution after turning on/off network, changing rpc, reloading extension
