### ISSUE TITLE
Single Mode feature customize for Parachain & Solo chains

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#331]
# Overview
When the chain wants to be unique or when it needs to provide some special features on SubWallet, **Single Mode** is born to solve this need.
The partners that cooperate with SubWallet in **Single Mode** can trigger this mode by
  - Turn into this mode the first time they install SubWallet and open specific domains of these chains.
  - They also have an interface to request turn into their **Single Mode** from their DApp or website.
When the **Single Mode** is turned on:
  - Many UI can be changed like the color, logo...
  - Delivery of some special features that only owned by the chain

# Todo
- [x] Create themes for single-mode
  - [x] Update theme structure for creating more than two theme types not only dark or light mode.
  - [x] SubSpace theme
  - [x] Change loading icon
- Turn on single-mode
  - [x] Single-mode predefined setting: JSON data of single-mode for each chain
    - network key: All network keys that trigger turn into single-mode
    - theme: key of existed theme
    - special tab (Not implemented right now)
    - autoTriggerDomain: domain regex is used to check trigger single-mode after the first install.
  - [x] Trigger single-mode on change network event
- [x] Disable feature change theme
- [x] Auto trigger if match domain pattern on install
- [x] Fix issue Account All not apply selected network after choosing another account and choose All Account again
- Trigger single mode on EVM or SubStrate provider (should be implemented in the new task)

**Single mode is disabled in #436 and needs to be enabled again**
- [x] Enabled single mode again
- [x] Auto enable networks in single modes
- [x] Single is not enabled in some computer, check this case with computer @Nghly (Chome ver 104) 

More improvement was moved into #623

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./532-merge-build-0.5.9-1662786975526.zip

Validation passed for cases:
- Open subspace network
- Not open subspace network
- Upgrade version
- Change theme
- Regression test all features
