### ISSUE TITLE
Rollback Single Mode

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#436]
# Overview
- Single mode is implemented #331 but needs more discussions and reviews before ready publishing.
- Pull request for this issue has been merged

# Solution
- Theme architect still can be used but single mode shouldn't be triggered before ready.

# Todo
- [x] Disable auto trigger single mode
- [x] Enable theme selection in settings
- [x] Fix wrong theme color after changing theme structure
  - Authentication
  - Firstime select network
