### ISSUE TITLE
Add support for new networks (new parachains winners)

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#842]
**Is your feature request related to a problem? Please describe.**

**- Kusama parachains:**

- [x] DAO IPCI: https://parachains.info/details/dao_ipci => Updated on pr #929 

**- Polkadot parachains:**

- OAK Network: https://parachains.info/details/oak_network => Resole on https://github.com/Koniverse/SubWallet-Chain/issues/6
- [x] Ajuna Network: https://parachains.info/details/ajuna_network => Updated on pr #929 
- [x] Totem KAPEX: https://parachains.info/details/totem => Updated on pr #929
